version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nguyen
      MYSQL_USER: nguyen
      MYSQL_PASSWORD: nguyen
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: nguyen
  web:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - db
volumes:
  db_data: {}
